# Generated by Django 6.0.3 on 2026-03-31 04:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Baia',
                'verbose_name_plural': 'Baias',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('faixa', models.CharField(choices=[('branca', 'Branca'), ('cinza', 'Cinza'), ('amarela', 'Amarela'), ('laranja', 'Laranja'), ('verde', 'Verde'), ('azul', 'Azul'), ('roxa', 'Roxa'), ('marrom', 'Marrom'), ('preta', 'Preta')], max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('peso_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('idade_min', models.PositiveIntegerField(blank=True, null=True)),
                ('idade_max', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['faixa', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('faixa', models.CharField(choices=[('branca', 'Branca'), ('cinza', 'Cinza'), ('amarela', 'Amarela'), ('laranja', 'Laranja'), ('verde', 'Verde'), ('azul', 'Azul'), ('roxa', 'Roxa'), ('marrom', 'Marrom'), ('preta', 'Preta')], max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('academia', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='atletas/')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atletas', to='campeonato.categoria')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Chave Principal', max_length=100)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('baia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaves', to='campeonato.baia')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaves', to='campeonato.categoria')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizado_em', models.DateTimeField(auto_now_add=True)),
                ('validado_por', models.CharField(blank=True, default='Apoio', max_length=100)),
                ('atleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='campeonato.atleta')),
                ('baia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='campeonato.baia')),
            ],
            options={
                'verbose_name': 'Check-In',
                'verbose_name_plural': 'Check-Ins',
                'ordering': ['-realizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Luta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('pontos', 'Por Pontos'), ('finalizacao', 'Por Finalização'), ('desclassificacao', 'Desclassificação'), ('bye', 'BYE (Passagem)'), ('pendente', 'Pendente'), ('em_andamento', 'Em Andamento')], default='pendente', max_length=20)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada')], default='aguardando', max_length=20)),
                ('pontos_atleta1', models.PositiveIntegerField(default=0)),
                ('pontos_atleta2', models.PositiveIntegerField(default=0)),
                ('rodada', models.PositiveIntegerField(default=1)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('realizada_em', models.DateTimeField(blank=True, null=True)),
                ('atleta1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lutas_como_atleta1', to='campeonato.atleta')),
                ('atleta2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lutas_como_atleta2', to='campeonato.atleta')),
                ('baia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lutas', to='campeonato.baia')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lutas', to='campeonato.chave')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitorias', to='campeonato.atleta')),
            ],
            options={
                'verbose_name': 'Luta',
                'verbose_name_plural': 'Lutas',
                'ordering': ['rodada', 'ordem'],
            },
        ),
    ]
