# Generated by Django 6.0.3 on 2026-03-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0002_atleta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='luta',
            name='penalizacoes_atleta1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='luta',
            name='penalizacoes_atleta2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='luta',
            name='vantagens_atleta1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='luta',
            name='vantagens_atleta2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
