# Generated by Django 6.0.3 on 2026-03-31 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0003_luta_penalizacoes_atleta1_luta_penalizacoes_atleta2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tatame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tatame',
                'verbose_name_plural': 'Tatames',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='chave',
            name='tatame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaves', to='campeonato.tatame'),
        ),
        migrations.AddField(
            model_name='luta',
            name='tatame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lutas', to='campeonato.tatame'),
        ),
    ]
