# Generated by Django 6.0.3 on 2026-03-31 11:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0004_tatame_chave_tatame_luta_tatame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('inscricoes_abertas', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['-data_evento', '-criado_em', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade_inscricao', models.CharField(choices=[('regular', 'Regular'), ('bolsa', 'Condição Especial / Bolsa')], default='regular', max_length=20)),
                ('comprovante_pagamento', models.FileField(blank=True, null=True, upload_to='comprovantes_pagamento/')),
                ('documento_bolsa', models.FileField(blank=True, null=True, upload_to='documentos_bolsa/')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes_inscricoes/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscrição no Campeonato',
                'verbose_name_plural': 'Inscrições no Campeonato',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='baia',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='atleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='campeonato.atleta'),
        ),
        migrations.AlterField(
            model_name='tatame',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='baia',
            name='campeonato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baias', to='campeonato.campeonato'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='campeonato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='campeonato.campeonato'),
        ),
        migrations.AddField(
            model_name='tatame',
            name='campeonato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tatames', to='campeonato.campeonato'),
        ),
        migrations.AddConstraint(
            model_name='baia',
            constraint=models.UniqueConstraint(fields=('campeonato', 'numero'), name='unique_baia_numero_por_campeonato'),
        ),
        migrations.AddConstraint(
            model_name='tatame',
            constraint=models.UniqueConstraint(fields=('campeonato', 'numero'), name='unique_tatame_numero_por_campeonato'),
        ),
        migrations.AddField(
            model_name='inscricaocampeonato',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='campeonato.atleta'),
        ),
        migrations.AddField(
            model_name='inscricaocampeonato',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='campeonato.campeonato'),
        ),
        migrations.AddField(
            model_name='inscricaocampeonato',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes', to='campeonato.categoria'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='inscricao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='campeonato.inscricaocampeonato'),
        ),
        migrations.AddConstraint(
            model_name='inscricaocampeonato',
            constraint=models.UniqueConstraint(fields=('atleta', 'campeonato'), name='unique_atleta_por_campeonato'),
        ),
    ]
