# Generated by Django 6.0.3 on 2026-03-31 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0005_campeonato_inscricaocampeonato_alter_baia_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_arbitro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Árbitro',
                'verbose_name_plural': 'Árbitros',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='luta',
            name='arbitro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lutas_arbitradas', to='campeonato.arbitro'),
        ),
        migrations.AddField(
            model_name='luta',
            name='finalizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lutas_finalizadas', to='campeonato.arbitro'),
        ),
        migrations.AddField(
            model_name='luta',
            name='iniciada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lutas_iniciadas', to='campeonato.arbitro'),
        ),
        migrations.CreateModel(
            name='ArbitroTatame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_tatame', to='campeonato.arbitro')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_arbitros', to='campeonato.campeonato')),
                ('tatame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_arbitros', to='campeonato.tatame')),
            ],
            options={
                'verbose_name': 'Vínculo Árbitro x Tatame',
                'verbose_name_plural': 'Vínculos Árbitro x Tatame',
                'ordering': ['tatame__numero', 'arbitro__nome'],
                'constraints': [models.UniqueConstraint(fields=('campeonato', 'tatame'), name='unique_tatame_por_campeonato_no_arbitro'), models.UniqueConstraint(fields=('arbitro', 'campeonato', 'tatame'), name='unique_vinculo_arbitro_tatame')],
            },
        ),
    ]
