# Generated by Django 6.0.3 on 2026-04-07 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0006_arbitro_luta_arbitro_luta_finalizada_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('pontos', 'Pontos'), ('vantagem', 'Vantagem'), ('penalizacao', 'Penalização'), ('finalizacao', 'Finalização')], max_length=20)),
                ('pontos', models.PositiveIntegerField(default=0, help_text='Pontos gerados. Para vantagem=1, penalização=0 (arbitro controla), finalização=0.')),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição na mesa do árbitro.')),
            ],
            options={
                'verbose_name': 'Tipo de Ação',
                'verbose_name_plural': 'Tipos de Ação',
                'ordering': ['categoria', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AcaoLuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('atleta', models.ForeignKey(blank=True, help_text='Atleta que executou a ação.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_realizadas', to='campeonato.atleta')),
                ('luta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='campeonato.luta')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_registradas', to='campeonato.arbitro')),
                ('tipo_acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='campeonato.tipoacao')),
            ],
            options={
                'verbose_name': 'Ação na Luta',
                'verbose_name_plural': 'Ações na Luta',
                'ordering': ['registrado_em'],
            },
        ),
    ]
