# Generated by Django 6.0.3 on 2026-04-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0011_allow_mesario_e_arbitro_por_tatame'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='pesagem_fim_dias',
            field=models.PositiveIntegerField(default=1, help_text='Encerramento da janela de pesagem: X dias antes do evento (ex: 1)'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='pesagem_inicio_dias',
            field=models.PositiveIntegerField(default=2, help_text='Abertura da janela de pesagem: X dias antes do evento (ex: 2)'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='prazo_pagamento_dias',
            field=models.PositiveIntegerField(default=3, help_text='Quantos dias antes do evento fecha o pagamento (ex: 3)'),
        ),
        migrations.AddField(
            model_name='inscricaocampeonato',
            name='pagamento_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaocampeonato',
            name='pagamento_confirmado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaocampeonato',
            name='pesagem_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaocampeonato',
            name='pesagem_realizada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaocampeonato',
            name='peso_aferido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
