# Generated by Django 6.0.3 on 2026-04-08 03:06

from django.db import migrations, models

DURACAO_POR_FAIXA = {
    'cinza': 240, 'amarela': 240, 'laranja': 240, 'verde': 240,
    'branca': 300, 'azul': 360, 'roxa': 420, 'marrom': 480, 'preta': 600,
}


def preencher_duracoes(apps, schema_editor):
    Categoria = apps.get_model('campeonato', 'Categoria')
    for cat in Categoria.objects.all():
        cat.duracao_segundos = DURACAO_POR_FAIXA.get(cat.faixa, 300)
        cat.save(update_fields=['duracao_segundos'])


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0012_prazo_pagamento_pesagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='duracao_segundos',
            field=models.PositiveIntegerField(default=300, help_text='Duração da luta em segundos — preenchido automaticamente pela faixa (regras IBJJF).'),
        ),
        migrations.RunPython(preencher_duracoes, migrations.RunPython.noop),
    ]
